#= require_tree ./adapters
#= require_tree ./controllers
#= require_tree ./models
#= require ./router.js.coffee
#= require_tree ./routes
#= require_tree ./components
#= require_tree ./helpers
#= require_tree ./templates
#= require_self